/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author tomas
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        JB_Ingresar = new javax.swing.JButton();
        JB_Listar = new javax.swing.JButton();
        JB_CrearCuenta = new javax.swing.JButton();
        JB_ActualizarDatos = new javax.swing.JButton();
        JB_EliminarCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Ingresar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        JB_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        JB_Ingresar.setText("INGRESAR");
        JB_Ingresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JB_Ingresar.setContentAreaFilled(false);
        JB_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(JB_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 270, 60));

        JB_Listar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        JB_Listar.setForeground(new java.awt.Color(255, 255, 255));
        JB_Listar.setText("LISTAR");
        JB_Listar.setActionCommand("");
        JB_Listar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JB_Listar.setContentAreaFilled(false);
        JB_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListarActionPerformed(evt);
            }
        });
        jPanel1.add(JB_Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 270, 60));

        JB_CrearCuenta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        JB_CrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        JB_CrearCuenta.setText("CREAR CUENTA");
        JB_CrearCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JB_CrearCuenta.setContentAreaFilled(false);
        JB_CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(JB_CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, 60));

        JB_ActualizarDatos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        JB_ActualizarDatos.setForeground(new java.awt.Color(255, 255, 255));
        JB_ActualizarDatos.setText("ACTUALIZAR DATOS");
        JB_ActualizarDatos.setActionCommand("");
        JB_ActualizarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JB_ActualizarDatos.setContentAreaFilled(false);
        JB_ActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ActualizarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(JB_ActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 280, 60));

        JB_EliminarCuenta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        JB_EliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        JB_EliminarCuenta.setText("ELIMINAR CUENTA");
        JB_EliminarCuenta.setActionCommand("");
        JB_EliminarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JB_EliminarCuenta.setContentAreaFilled(false);
        JB_EliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(JB_EliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu vacio.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_IngresarActionPerformed
        Ingresar newframe = new Ingresar();
        newframe.setVisible(true);
        this.dispose();
        newframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_IngresarActionPerformed

    private void JB_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListarActionPerformed
        ListUsuario newframe = new ListUsuario();
        newframe.setVisible(true);
        this.dispose();
        newframe.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_JB_ListarActionPerformed

    private void JB_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearCuentaActionPerformed
        CrearCuenta newframe= new CrearCuenta();
        newframe.setVisible(true);
        this.dispose();
        newframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_CrearCuentaActionPerformed

    private void JB_ActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ActualizarDatosActionPerformed
        ActualizarDatos newframe=new ActualizarDatos();
        newframe.setVisible(true);
        this.dispose();
        newframe.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_JB_ActualizarDatosActionPerformed

    private void JB_EliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminarCuentaActionPerformed
        Eliminar newframe = new Eliminar();
        newframe.setVisible(true);
        this.dispose();
        newframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_EliminarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_ActualizarDatos;
    private javax.swing.JButton JB_CrearCuenta;
    private javax.swing.JButton JB_EliminarCuenta;
    private javax.swing.JButton JB_Ingresar;
    private javax.swing.JButton JB_Listar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
